#ifndef ESTADOS_H
#define ESTADOS_H

// #include "../headers/estados/Q0.h"

// #include "../headers/estados/Q1.h"
// #include "../headers/estados/Q2.h"
// #include "../headers/estados/Q3.h"
// #include "../headers/estados/Q4.h"
// #include "../headers/estados/Q5.h"
// #include "../headers/estados/Q6.h"
// #include "../headers/estados/Q7.h"
// #include "../headers/estados/Q8.h"
// #include "../headers/estados/Q9.h"
// #include "../headers/estados/Q10.h"

// #include "../headers/estados/Q11.h"
// #include "../headers/estados/Q12.h"
// #include "../headers/estados/Q13.h"
// #include "../headers/estados/Q14.h"
// #include "../headers/estados/Q15.h"
// #include "../headers/estados/Q16.h"
// #include "../headers/estados/Q17.h"
// #include "../headers/estados/Q18.h"
// #include "../headers/estados/Q19.h"
// #include "../headers/estados/Q20.h"

// #include "../headers/estados/Q21.h"
// #include "../headers/estados/Q22.h"
// #include "../headers/estados/Q23.h"
// #include "../headers/estados/Q24.h"
// #include "../headers/estados/Q25.h"
// #include "../headers/estados/Q26.h"
// #include "../headers/estados/Q27.h"
// #include "../headers/estados/Q28.h"
// #include "../headers/estados/Q29.h"
// #include "../headers/estados/Q30.h"

// #include "../headers/estados/Q31.h"
// #include "../headers/estados/Q32.h"
// #include "../headers/estados/Q33.h"
// #include "../headers/estados/Q34.h"
// #include "../headers/estados/Q35.h"
// #include "../headers/estados/Q36.h"
// #include "../headers/estados/Q37.h"
// #include "../headers/estados/Q38.h"
// #include "../headers/estados/Q39.h"
// #include "../headers/estados/Q40.h"

// #include "../headers/estados/Q41.h"
// #include "../headers/estados/Q42.h"
// #include "../headers/estados/Q43.h"
// #include "../headers/estados/Q44.h"
// #include "../headers/estados/Q45.h"
// #include "../headers/estados/Q46.h"
// #include "../headers/estados/Q47.h"
// #include "../headers/estados/Q48.h"
// #include "../headers/estados/Q49.h"
// #include "../headers/estados/Q50.h"

// #include "../headers/estados/Q51.h"
// #include "../headers/estados/Q52.h"
// #include "../headers/estados/Q53.h"
// #include "../headers/estados/Q54.h"
// #include "../headers/estados/Q55.h"
// #include "../headers/estados/Q56.h"
// #include "../headers/estados/Q57.h"
// #include "../headers/estados/Q58.h"
// #include "../headers/estados/Q59.h"
// #include "../headers/estados/Q60.h"

// #include "../headers/estados/Q61.h"
// #include "../headers/estados/Q62.h"
// #include "../headers/estados/Q63.h"
// #include "../headers/estados/Q64.h"
// #include "../headers/estados/Q65.h"
// #include "../headers/estados/Q66.h"
// #include "../headers/estados/Q67.h"
// #include "../headers/estados/Q68.h"
// #include "../headers/estados/Q69.h"
// #include "../headers/estados/Q70.h"

// #include "../headers/estados/Q71.h"
// #include "../headers/estados/Q72.h"
// #include "../headers/estados/Q73.h"
// #include "../headers/estados/Q74.h"
// #include "../headers/estados/Q75.h"
// #include "../headers/estados/Q76.h"
// #include "../headers/estados/Q77.h"
// #include "../headers/estados/Q78.h"
// #include "../headers/estados/Q79.h"
// #include "../headers/estados/Q80.h"

// #include "../headers/estados/Q81.h"
// #include "../headers/estados/Q82.h"
// #include "../headers/estados/Q83.h"
// #include "../headers/estados/Q84.h"
// #include "../headers/estados/Q85.h"
// #include "../headers/estados/Q86.h"
// #include "../headers/estados/Q87.h"
// #include "../headers/estados/Q88.h"
// #include "../headers/estados/Q89.h"
// #include "../headers/estados/Q90.h"

// #include "../headers/estados/Q91.h"
// #include "../headers/estados/Q92.h"
// #include "../headers/estados/Q93.h"
// #include "../headers/estados/Q94.h"
// #include "../headers/estados/Q95.h"
// #include "../headers/estados/Q96.h"
// #include "../headers/estados/Q97.h"
// #include "../headers/estados/Q98.h"
// #include "../headers/estados/Q99.h"
// #include "../headers/estados/Q100.h"

// #include "../headers/estados/Q101.h"
// #include "../headers/estados/Q102.h"
// #include "../headers/estados/Q103.h"

#endif